name: Scheduled Postman Collection Run

on:
  schedule:
    - cron: '0/10 * * * *'  # Schedule to run daily at midnight (UTC)

jobs:
  collection_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Newman
        run: npm install -g newman

      - name: Run Collection 1
        run: newman run "Mocking with fruits.postman_collection.json"

  collection_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Newman
        run: npm install -g newman

      - name: Run Collection 2
        run: newman run "Functional Testing and Automation.postman_collection.json"

  # Add more jobs for additional collections as needed
